#!/bin/bash

set -euo pipefail
set -x

#
# Shim OCAMLLIB so that we can write topfind there
#

mkdir -p $cur__install/lib/ocaml
cd $cur__install/lib/ocaml

for filename in `ls -1 $ocaml__install/lib/ocaml`; do
  ln -s $ocaml__install/lib/ocaml/$filename $filename;
done

#
# Build
#

cd $cur__root

export OCAMLLIB="$cur__install/lib/ocaml"

./configure \
  -bindir $cur__install/bin \
  -sitelib $cur__install/lib \
  -mandir $cur__install/man \
  -config $cur__install/lib/findlib.conf \
  -no-custom \
  -no-camlp4

make all
make opt
make install

(opam-installer --prefix=$cur__install || true)
